language: generic 
sudo: required
services:
  - docker
env:
  - CI=true
before_install:
  - docker build -t mosleim/praktekdocker -f Dockerfile.dev .

script:
  - docker run  mosleim/praktekdocker npm run test
