language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t mosleim/praktekdocker -f Dockerfile.dev .

script:
  - docker run -e CI=true  mosleim/praktekdocker npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "praktekdocker"
  env: "Praktekdocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-971278214976"
  bucket_path: "praktekdocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
